### ISSUE TITLE
Issue-Update README.md

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/123#5]
Automated Review Comments
Issues in contracts/Ayusocoin.sol:
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')

**Comment by johnsmith0212** [comment]
I got it.
